### ISSUE TITLE
bin/certbot-register raises ExecutableNotFound

### ISSUE THREAD

**Issue by wamdam** [veit/userland-certbot#1]
When following the readme and calling

```
$ bin/certbot-register
```

this exception is logged into certbot.log:

```
Traceback (most recent call last):
  File "/home/dk/tmp/certbot/userland-certbot/bin/certbot", line 37, in <module>
    sys.exit(certbot.main.main())
  File "/home/dk/tmp/certbot/userland-certbot/eggs/certbot-0.8.0-py2.7.egg/certbot/main.py", line 708, in main
    setup_logging(config, _cli_log_handler, logfile='letsencrypt.log')
  File "/home/dk/tmp/certbot/userland-certbot/eggs/certbot-0.8.0-py2.7.egg/certbot/main.py", line 622, in setup_logging
    cli_handler = cli_handler_factory(config, level, fmt)
  File "/home/dk/tmp/certbot/userland-certbot/eggs/certbot-0.8.0-py2.7.egg/certbot/main.py", line 609, in _cli_log_handler
    handler = log.DialogHandler()
  File "/home/dk/tmp/certbot/userland-certbot/eggs/certbot-0.8.0-py2.7.egg/certbot/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/home/dk/tmp/certbot/userland-certbot/eggs/python2_pythondialog-3.4.0-py2.7.egg/dialog.py", line 1015, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "/home/dk/tmp/certbot/userland-certbot/eggs/python2_pythondialog-3.4.0-py2.7.egg/dialog.py", line 479, in _path_to_executable
    "can't find the executable for the dialog-like "
ExecutableNotFound
```

**Comment by MichaelHierweck** [comment]
Certbot depends on the system package "dialog".

Please try to add the --text parameter to the certbot call in bin/certbot-register (as in certbot-runner). But don't add the --non-interactive parameter.

Do this work for you?

We would add the --text by default then. See PR #2.

**Comment by MichaelHierweck** [comment]
Closing since PR #2 has been merged.
Please feel free to reopen this issue if the problem still appears in your setup after upgrading.
